export const inventoryData = [
    {
      id: 1,
      image: "https://via.placeholder.com/50",
      name: "Hand Sanitizer",
      category: "Sanitizer",
      availabilityStatus: "available",
      qtyInStock: 100,
      qtyInOrder: 50,
      action: "Restock",
    },
    {
      id: 2,
      image: "https://via.placeholder.com/50",
      name: "PPE Kit",
      category: "PPE",
      availabilityStatus: "unavailable",
      qtyInStock: 0,
      qtyInOrder: 20,
      action: "Order",
    },
    {
      id: 3,
      image: "https://via.placeholder.com/50",
      name: "Face Mask",
      category: "Mask",
     availabilityStatus: "available",
      qtyInStock: 300,
      qtyInOrder: 100,
      action: "Restock",
    },
    {
      id: 4,
      image: "https://via.placeholder.com/50",
      name: "N95 Respirator",
      category: "Mask",
      availabilityStatus: "available",
      qtyInStock: 150,
      qtyInOrder: 30,
      action: "Restock",
    },
    {
      id: 5,
      image: "https://via.placeholder.com/50",
      name: "Disposable Gloves",
      category: "Gloves",
      availabilityStatus: "unavailable",
      qtyInStock: 0,
      qtyInOrder: 500, 
      action: "Order",
    },
    {
      id: 6,
      image: "https://via.placeholder.com/50",
      name: "Thermometer",
      category: "Medical Equipment",
      availabilityStatus: "available",
      qtyInStock: 80,
      qtyInOrder: 10,
      action: "Restock",
    },
    {
      id: 7,
      image: "https://via.placeholder.com/50",
      name: "Face Shield",
      category: "PPE",
      availabilityStatus: "available",
      qtyInStock: 200,
      qtyInOrder: 50,
      action: "Restock",
    },
    {
      id: 8,
      image: "https://via.placeholder.com/50",
      name: "Alcohol Wipes",
      category: "Sanitizer",
      availabilityStatus: "available",
      qtyInStock: 400,
      qtyInOrder: 100,
      action: "Restock",
    },
    {
      id: 9,
      image: "https://via.placeholder.com/50",
      name: "Surgical Gown",
      category: "PPE",
      availabilityStatus: "unavailable",
      qtyInStock: 0,
      qtyInOrder: 75,
      action: "Order",
    },
    {
      id: 10,
      image: "https://via.placeholder.com/50",
      name: "Infrared Thermometer",
      category: "Medical Equipment",
      availabilityStatus: "available",
      qtyInStock: 120,
      qtyInOrder: 30,
      action: "Restock",
    },
  ];
  